name: Build and publish docker image

on:
  push:
    branches:
      - master

jobs:
  build-and-publish-image:
    name: Build and publish image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/capofcave/haste-server:latest

      - name: Login to ghcr
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Push image to ghcr
        run: docker push ghcr.io/capofcave/haste-server:latest
